services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: job-market
    ports:
      - "127.0.0.1:8000:8000"
      - "127.0.0.1:8050:8050"
    volumes:
      - job-market-data:/app/data

volumes:
  job-market-data: