---
title: Job Market app workflow
---
stateDiagram-v2
    [*] --> DockerCompose
    DockerCompose --> Dockerfile
   

    state Dockerfile {[*] --> InstallPython
    InstallPython --> installRequirements
    installRequirements --> entrypoint
    }
    
    
    Dockerfile --> entrypoint
    entrypoint: entrypoint.sh
    state entrypoint {
        [*] --> lintingCode
        lintingCode --> src.data.make_dataset : run
        src.data.make_dataset --> checkDatabase : run
        checkDatabase --> startMap : run
        startMap --> [*]
    } 
   